version: '3.8'

services:
  admin:
    build:
      context: ./Admin
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      # Optional: Mount .env file directly if env_file doesn't work
      # - ./.env:/app/.env
    restart: always

  user:
    build:
      context: ./User
    ports:
      - "8086:8086"
    env_file:
      - ./.env
    # volumes:
      # Optional: Mount .env file directly
      # - ./.env:/app/.env
    restart: always
